# Supported funding platforms.
# More info: https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [dev-xo]
patreon: # ...
open_collective: # ...
ko_fi: # ...
tidelift: # ...
community_bridge: # ...
liberapay: # ...
issuehunt: # ...
otechie: # ...
lfx_crowdfunding: # ...
custom: # ...
